// THIS FILE IS AUTO-GENERATED BY `config.py` -- EDIT AT YOUR OWN RISK

#ifndef DRAM_TIMING_h
#define DRAM_TIMING_h

#include <cstdint>

////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////

constexpr uint64_t CL = 39;
constexpr uint64_t CWL = 37;
constexpr uint64_t tRCD = 39;
constexpr uint64_t tRP = 39;
constexpr uint64_t tRAS = 77;
constexpr uint64_t tRTP = 18;
constexpr uint64_t tWR = 72;

constexpr uint64_t tCCD_S = 8;
constexpr uint64_t tCCD_S_WR = 8;
constexpr uint64_t tCCD_S_WTR = 51;
constexpr uint64_t tCCD_S_RTW = 51;

constexpr uint64_t tCCD_L = 12;
constexpr uint64_t tCCD_L_WR = 48;
constexpr uint64_t tCCD_L_WTR = 69;
constexpr uint64_t tCCD_L_RTW = 69;

constexpr uint64_t tRRD_S = 8;
constexpr uint64_t tRRD_L = 12;
constexpr uint64_t tFAW = 32;

constexpr uint64_t tRFC = 984;
constexpr uint64_t tREFI = 9375;

////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////

#endif  // DRAM_TIMING_h

