'''
    author: Suhas Vittal
    date:   4 December 2024
'''

####################################################################
####################################################################

GEN_DIR = '_generated'

CONSTANTS_FILE = f'{GEN_DIR}/constants.h'
MEMSYS_FILE = f'{GEN_DIR}/memsys_decl.h'

AUTOGEN_HEADER = '// THIS FILE IS AUTO-GENERATED BY `config.py` -- EDIT AT YOUR OWN RISK'

def set_config_name(name: str):
    pass  # THIS FUNCTION SHOULD CHANGE THE VALUE OF ALL FILES HERE (`GEN_DIR` becomes `_generated/{name}`)

####################################################################
####################################################################


